version: "3.9"

services:
  api:
    image: jamesguan777/pokemon-tracker:1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - rabbit
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/

  rabbit:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # management UI

  dashboard:
    image: jamesguan777/pokemon-dashboard:1.0.0
    ports:
      - "8080:80"
    volumes:
      - ./front-end/dashboard/public/config.js:/usr/share/nginx/html/config.js:ro
    depends_on:
      - api